54 resolve timeseries paths relative to template position
FEAT-ML/scengen pull request #67
Opened 2024-08-13 16:17 UTC by fxnitsch

2024-08-13 16:33 UTC, fxnitsch commented
@dlr-cjs: please review

2024-08-14 07:11 UTC, dlr-cjs requested changes
Ok, minor revision requested

2024-08-14 07:11 UTC, dlr-cjs commented on scengen/generator.py
> +        _replace_timeseries_path_in(scenario["StringSets"][string_set], path_to_append)
Verstehe ich nicht: StringSets sind doch nur Namen - da sollten keine Pfade enthalten sein

2024-08-14 07:11 UTC, dlr-cjs commented on scengen/generator.py
> +        _replace_timeseries_path_in(agent.get("Attributes", {}), path_to_append)
Ich glaube das ist nicht safe ggü. der verschiedenen erlaubten Schreibweisen von "Attributes"... wenn man das direkt über FAME-Io erreichen könnte, wäre es glaub sicherer

2024-08-14 07:11 UTC, dlr-cjs commented on scengen/generator.py
> +            if attribute_value.lower().endswith(".csv"):
Also das geht ist aber auch nicht sooo sicher, weil die Prüfung auf den Attributtyp im Schema fehlt.
Ich würde das so lassen, aber schlage gleichzeitig vor in FAME-Io helper-Methode zur Anpassung von Pfaden einzuführen?

2024-08-14 11:16 UTC, dlr-cjs approved these changes

2024-08-14 11:16 UTC, merged