59 auto linking broken
FEAT-ML/scengen pull request #69
Opened 2024-08-28 07:23 UTC by fxnitsch

This PR is addressing #59 and
* fixes the linking of dynamically created agents
* adds (better) warning messages if the user provided invalid configurations
* changes the attribute type of `external_ids` from dict to list

Furthermore, it 
* fixes an inconsistency that the `trace_file` is read relatively from the location of the `GeneratorConfig` like all other file paths

Please find a complete configuration for testing purposes attached.
[testing_configuration_issue-59.zip](https://github.com/user-attachments/files/16777920/testing_configuration_issue-59.zip)

2024-09-13 12:46 UTC, dlr-cjs requested changes
Please fix issues as discussed

2024-09-16 06:54 UTC, fxnitsch commented on scengen/generator.py
> +def _raise_if_missing_match(create_config: List[Dict]) -> None:
done

2024-09-16 06:54 UTC, fxnitsch commented on scengen/generator.py
> +        add_agents(config, options, scenario)
done

2024-09-16 06:54 UTC, fxnitsch commented on scengen/generator.py
> +def add_agents(config: dict, options: dict, scenario: dict) -> None:
done

2024-09-16 06:54 UTC, fxnitsch commented on scengen/generator.py
> +    for created_agent in config["create"]:
done

2024-09-16 06:54 UTC, fxnitsch commented on scengen/generator.py
> +def _raise_if_no_replacement_identifier_in(contracts: List[Dict]) -> None:
removed

2024-09-16 06:55 UTC, fxnitsch commented on scengen/generator.py
> +    for created_agent in config["create"]:
done

2024-09-16 06:57 UTC, fxnitsch commented
@dlr-cjs: all issues resolved. please also find an updated testing configuration in the PR header description.

2024-09-17 08:08 UTC, fxnitsch commented
@dlr-cjs: changed `external_ids` to dict and allow list of str/int values, improved pattern matching to be more robust

please review

2024-09-17 13:20 UTC, dlr-cjs approved these changes
Works nicely. generator.py is too large now - I recommend creating a subpackage from it - in a **separate** issue.

2024-09-17 13:35 UTC, merged